apiVersion: v1
kind: Service
metadata:
  name: seata-example-service
  labels:
    name: seata-example-service
spec:
  type: NodePort
  ports:
  - port: 8102
    name: "account"
    targetPort: 8102
    protocol: TCP
  - port: 8100
    name: "storage"
    targetPort: 8100
    protocol: TCP
  selector:
    app: seata-example