# permissions for end users to edit seataservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: seataserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: seata-k8s
    app.kubernetes.io/part-of: seata-k8s
    app.kubernetes.io/managed-by: kustomize
  name: seataserver-editor-role
rules:
- apiGroups:
  - operator.seata.apache.org
  resources:
  - seataservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.seata.apache.org
  resources:
  - seataservers/status
  verbs:
  - get
