apiVersion: operator.seata.apache.org/v1alpha1
kind: SeataServer
metadata:
  name: seata-server
  namespace: default
spec:
  serviceName: seata-server-cluster
  replicas: 2
  image: seataio/seata-server:2.0.0
  store:
    resources:
      requests:
        storage: 5Gi
