apiVersion: operator.seata.apache.org/v1alpha1
kind: SeataServer
metadata:
  name: seata-server
  namespace: default
spec:
  serviceName: seata-server-cluster
  replicas: 1
  image: seataio/seata-server:latest
  persistence:
    volumeReclaimPolicy: Delete
  store:
    resources:
      requests:
        storage: 5Gi
  env:
    - name: console.user.username
      value: seata
    - name: console.user.password
      valueFrom:
        secretKeyRef:
          name: seata
          key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: seata
type: Opaque
data:
  password: MTIzNDU2
