apiVersion: operator.seata.apache.org/v1alpha1
kind: SeataServer
metadata:
  name: seata-server
  namespace: default
spec:
  serviceName: seata-server-cluster
  replicas: 1
  image: seataio/seata-server:latest
  persistence:
    volumeReclaimPolicy: Delete
