apiVersion: v1
kind: Service
metadata:
  name: seata-service
  labels:
    name: seata-service
spec:
  type: NodePort
  ports:
  - port: 8091
    name: "fescar"
    protocol: TCP
  - port: 3306
    name: "mysql"
    targetPort: 3306
    protocol: TCP
  - port: 8848
    name: "nacos"
    targetPort: 8848
    protocol: TCP
  selector:
    app: seata